const mongoose = require("mongoose");
const { Schema } = mongoose;

const offersSchema = new Schema({
  label: { type: String, required: true },
  values: { type: String, required: true },
});

const productSchema = new Schema({
  name: { type: String, required: true },
  title: { type: String, required: true },
  category: { type: String, required: true },
  subCategory: { type: String, required: true },
  images: [
    {
      public_id: {
        type: String,
        required: true,
      },
      url: {
        type: String,
        required: true,
      },
    },
  ],


  description: { type: String, required: true },
  basicInfo: { type: String, required: true },
  price: { type: String, required: true },
  mfr: { type: String, required: true },
  mfrNo: { type: String, required: true },
  partNumber: { type: String, required: true },
  inventory: { type: String, required: true },
  brand: { type: String, required: true },
  ram: { type: String, required: true },
  storage: { type: String, required: true },
  compatible: { type: String, required: true },
  material: { type: String, required: true },
  type: { type: String, required: true },
  factoryLead: { type: String, required: true },
  lifeCycle: { type: String, required: true },
  contactPlating: { type: String, required: true },
  housingMaterial: { type: String, required: true },
  processor: { type: String, required: true },
  capacity: { type: String, required: true },
  pinsNo: { type: String, required: true },
  ramProcessor: { type: String, required: true },
  operatingSystem: { type: String, required: true },
  memory: { type: String, required: true },
  memoryTechnology: { type: String, required: true },
  size: { type: String, required: true },
  antenna: { type: String, required: true },
  frequencyBand: { type: String, required: true },
  cells: { type: String, required: true },
  cores: { type: String, required: true },
  designedFor: { type: String, required: true },
  wiredWireless: { type: String, required: true },
  CPC: { type: String, required: true },
  connectivity: { type: String, required: true },
  refillingType: { type: String, required: true },
  panelType: { type: String, required: true },
  screenForm_factor: { type: String, required: true },
  chipSet: { type: String, required: true },
  displayTechnology: { type: String, required: true },
  colorType: { type: String, required: true },
  color: { type: String, required: true },
  hsnCode: { type: String, required: true },
  sku: { type: String, required: true },
  stock: { type: String, required: true },
  priceBefore: { type: String, required: true },
  maxOrderQty: { type: String, required: true },
  minOrderQty: { type: String, required: true },
  primaryProducts: { type: String, required: true },
  primePartner: { type: String, required: true },
  length: { type: String, required: true },
  breadth: { type: String, required: true },
  imageTitle: { type: String, required: true },
  height: { type: String, required: true },
  weight: { type: String, required: true },
  RadiationHardening: { type: String, required: true },
  PbfreeCode: { type: String, required: true },
  IECConformance: { type: String, required: true },
  FilterFeature: { type: String, required: true },
  MixedContacts: { type: String, required: true },
  Option: { type: String, required: true },
  TotalNumberOfContacts: { type: String, required: true },
  Orientation: { type: String, required: true },
  Depth: { type: String, required: true },
  ReachComplianceCode: { type: String, required: true },
  CurrentRating: { type: String, required: true },
  Frequency: { type: String, required: true },
  ApprovalAgency: { type: String, required: true },
  LeadPitch: { type: String, required: true },
  NumberOfContacts: { type: String, required: true },
  MatingInformation: { type: String, required: true },
  ContactGender: { type: String, required: true },
  EmptyShell: { type: String, required: true },
  OperatingSupplyVoltage: { type: String, required: true },
  BackshellType: { type: String, required: true },
  BodyOrShellStyle: { type: String, required: true },
  Interface: { type: String, required: true },
  ELV: { type: String, required: true },
  MaxSupplyVoltage: { type: String, required: true },
  MinSupplyVoltage: { type: String, required: true },
  CouplingType: { type: String, required: true },
  NumberOfPorts: { type: String, required: true },
  AccessoryType: { type: String, required: true },
  NumberOfPoles: { type: String, required: true },
  Sealable: { type: String, required: true },
  Density: { type: String, required: true },
  NumberOfDrivers: { type: String, required: true },
  OutsideDiameter: { type: String, required: true },
  NumberOfReceivers: { type: String, required: true },
  HeadDiameter: { type: String, required: true },

  offers: [offersSchema],
});

const Product = mongoose.model("product", productSchema);

module.exports = Product;
